/**
 * Factory function to create Prisma Client instance
 * Uses require for @prisma/client in both test and production environments
 */
export async function createPrismaClient() {
  // Use the default @prisma/client location generated by Prisma
  // This works in both Jest tests and production
  const { PrismaClient } = require('@prisma/client');
  return new PrismaClient();
}
